### ISSUE TITLE
How do i run it?

### ISSUE THREAD

**Issue by SGauts** [mercedesbenzio/ts-spec-bootstrapper#11]
After installing how do i run it?

**Comment by FranzSkuffka** [comment]
```
ts-spec-bootstrapper --root='src/app/'
```

**Comment by SGauts** [comment]
Do I have to run this command in the cli?
I have added this line to the dependency but it is not generating the spec file automatically!!

**Comment by FranzSkuffka** [comment]
@Sanderand

**Comment by SGauts** [comment]
I have added ts-spec-bootstrapper --root='src/app/' to my package the json file. I have also installed it to npm, I have also created the spec file with the same name. But it does not do anything. How do I get it to create the test cases automatically?
Please help me, it's very important.

**Comment by FranzSkuffka** [comment]
_urgently calling @Sanderand and @naflcosta for help_

**Comment by Sanderand** [comment]
@SGauts which operating system, node and npm version are you using? what is the console output after running that script?

**Comment by SGauts** [comment]
I have a MAC OS Mojave with node: '10.15.1' and npm: '6.9.0'.

At the console when I run the npm install command it gets the dependency installed as a dev dependency but then nothing happens.

I have tried pasting ts-spec-bootstrapper --root='src/app/' in the package.json file but nothing happens.

Please tell me the exact command to run in the terminal to automatically generate the spec file with the unit test functions.

**Comment by Sanderand** [comment]
add this to your package.json in the scripts section:

`"ts-spec-bootstrapper": "ts-spec-bootstrapper --root='src/app/'"``

to execute the script now run in your terminal:

`npm run ts-spec-bootstrapper`

please let me know. what the terminal outputs now.

**Comment by SGauts** [comment]
Administrators-MacBook-Pro-3:forms-reactive-start $ npm run ts-spec-bootstrapper

> my-first-app@0.0.0 ts-spec-bootstrapper /Users/angular/forms-reactive-start
> ts-spec-bootstrapper --root='src/app/'

sh: ts-spec-bootstrapper: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! my-first-app@0.0.0 ts-spec-bootstrapper: `ts-spec-bootstrapper --root='src/app/'`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the my-first-app@0.0.0 ts-spec-bootstrapper script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shgautam/.npm/_logs/2019-03-22T06_13_04_175Z-debug.log
Administrators-MacBook-Pro-3:forms-reactive-start $

**Comment by Sanderand** [comment]
do you have this in your package.json?
```
"scripts": {
  "ts-spec-bootstrapper": "ts-spec-bootstrapper --root='src/app/'"`
}
```

did you do?
```
npm i ts-spec-bootstrapper
```

then you should be able to run this from your project root directory
```
npm run ts-spec-bootstrapper
```

########

here's a minimal example that should work. can you try adding the below files to a new directory, then run `npm i` and then run `npm run ts-spec-bootstrapper`?

package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "ts-spec-bootstrapper": "ts-spec-bootstrapper --root=src"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ts-spec-bootstrapper": "^0.2.0"
  }
}
```

src/test.ts
```
function asd() {
  if (true) {
    return null;
  }
}
```

**Comment by SGauts** [comment]
Yes it ran but did not generate any .spec file with unit test cases

**Comment by SGauts** [comment]
READ

  Files: 2
  Functions: 0
  Arrow functions: 0
  Methods: 0


BRANCHES

  Then: 0
  Else: 0
  Else If: 0
  Implicit Else: 0


FUNCTIONS SKIPPED

  Because already tested: 0
  Because private: 0
  Because protected: 0


WRITTEN

  Files: 0
  Tests: 0


(Finished in 25 ms)

**Comment by SGauts** [comment]
But i had the entire app.component.ts file which contained the following:

import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators, FormArray } from '@angular/forms';
import { Observable } from 'rxjs/Observable';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  genders = ['male', 'female'];
  signupForm : FormGroup;
  forbiddenUsernames= ['Chris', 'Anna'];

  ngOnInit() {
    this.signupForm = new FormGroup({
      'userData': new FormGroup({
        'username': new FormControl(null, [Validators.required, this.forbiddenNames.bind(this) ]),
      'email': new FormControl(null, [Validators.required, Validators.email], this.forbiddenEmails),
      
      }),
      'gender': new FormControl('male'),
      'hobbies': new FormArray([])
      
    });this.signupForm.statusChanges.subscribe(
      (status) => console.log(status)
    );
    this.signupForm.setValue({
      'userData': {
        'username': 'Max',
        'email' : 'max@test.com'},

        'gender': 'male',
        'hobbies': []
      });
    }

  
  onSubmit(){
    console.log(this.signupForm);
  }
  onAddHobby(){
    const control = new FormControl(null, Validators.required );
    (<FormArray>this.signupForm.get('hobbies')).push(control);
  }
  forbiddenNames(control:FormControl ): {[s:string]: boolean}{
  if (this.forbiddenUsernames.indexOf(control.value) !== -1 ) {
    return {'nameIsForbidden': true};
  }
  return null;
}

forbiddenEmails(control:FormControl): Promise<any> | Observable<any>  {
const promise = new Promise<any>((resolve, reject)=> {
setTimeout( ()=> {
  if(control.value === 'test@test.com'){
    resolve({'emailIsForbidden': true});
  }
  else{
    resolve(null);
  }
}, 1500);
}  );
return promise;
}
}

**Comment by Sanderand** [comment]
This issue is closed then. The spec generator ran successfully. Please open a new issue for your problem with details that allow me to reproduce it.
