### ISSUE TITLE
Not creating any spec file / Not writing the unit test cases

### ISSUE THREAD

**Issue by SGauts** [mercedesbenzio/ts-spec-bootstrapper#12]
After running the npm run command it runs but no .spec file is created. No unit test cases are created for the .ts file in the .spec file.
Please help.

**Comment by Sanderand** [comment]
Please provide information to help me reproduce this problem:
- script extract from package.json
- Which command are you running and what is the console output when running the test generator
- npm version
- node version
- operating system

**Comment by SGauts** [comment]
Package.json file is as follows:

{
  "name": "my-first-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "ts-spec-bootstrapper": "ts-spec-bootstrapper --root='src/app/'"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "bootstrap": "3.3.7",
    "core-js": "^2.5.4",
    "rxjs": "6.3.3",
    "rxjs-compat": "^6.1.0",
    "ts-spec-bootstrapper": "^0.2.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.0",
    "@angular/cli": "~6.0.0",
    "@angular/compiler-cli": "^6.0.0",
    "@angular/language-service": "^6.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}


NPM Version 6.9.0
Node Version: v10.15.1
Mac OS Mojave 

i ran the following command npm run ts-spec-bootstrapper

The output that i got

> ts-spec-bootstrapper --root='src/app/'


  ___________    _____
 /_  __/ ___/   / ___/____  ___  _____
  / /  \__ \    \__ \/ __ \/ _ \/ ___/
 / /  ___/ /   ___/ / /_/ /  __/ /__
/_/  /____/   /____/ .___/\___/\___/
                    /_/

Generating missing tests for PUBLIC methods, functions and arrow functions


################################################

READ

  Files: 2
  Functions: 0
  Arrow functions: 0
  Methods: 0


BRANCHES

  Then: 0
  Else: 0
  Else If: 0
  Implicit Else: 0


FUNCTIONS SKIPPED

  Because already tested: 0
  Because private: 0
  Because protected: 0


WRITTEN

  Files: 0
  Tests: 0


(Finished in 25 ms)

################################################


Please help me generating the right output.

**Comment by Sanderand** [comment]
Thanks for the outputs. Now I can get an idea of where the problem might be. You can see in the output of `ts-spec-bootstrapper --root='src/app/'` that it only reads two `.ts` files. Is that correct? Does your `/src/app` directory only contain 2 `.ts` files? If so, are there functions/methods/arrow-functions in those 2 files?

**Comment by SGauts** [comment]
Yes, there are only 2 .ts files in src/app. 
And yes there are also functions present in the file but it is not being read and no test cases are being generated.

**Comment by Sanderand** [comment]
Ok, that's weird. Sorry for the inconveniences. Would you mind sending me an extract of one of the files so that I can re-test this on my machine and work out a bug fix?

**Comment by SGauts** [comment]
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators, FormArray } from '@angular/forms';
import { Observable } from 'rxjs/Observable';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  genders = ['male', 'female'];
  signupForm : FormGroup;
  forbiddenUsernames= ['Chris', 'Anna'];

  ngOnInit() {
    this.signupForm = new FormGroup({
      'userData': new FormGroup({
        'username': new FormControl(null, [Validators.required, this.forbiddenNames.bind(this) ]),
      'email': new FormControl(null, [Validators.required, Validators.email], this.forbiddenEmails),
      
      }),
      'gender': new FormControl('male'),
      'hobbies': new FormArray([])
      
    });this.signupForm.statusChanges.subscribe(
      (status) => console.log(status)
    );
    this.signupForm.setValue({
      'userData': {
        'username': 'Max',
        'email' : 'max@test.com'},

        'gender': 'male',
        'hobbies': []
      });
    }

  
  onSubmit(){
    console.log(this.signupForm);
  }
  onAddHobby(){
    const control = new FormControl(null, Validators.required );
    (<FormArray>this.signupForm.get('hobbies')).push(control);
  }
  forbiddenNames(control:FormControl ): {[s:string]: boolean}{
  if (this.forbiddenUsernames.indexOf(control.value) !== -1 ) {
    return {'nameIsForbidden': true};
  }
  return null;
}

forbiddenEmails(control:FormControl): Promise<any> | Observable<any>  {
const promise = new Promise<any>((resolve, reject)=> {
setTimeout( ()=> {
  if(control.value === 'test@test.com'){
    resolve({'emailIsForbidden': true});
  }
  else{
    resolve(null);
  }
}, 1500);
}  );
return promise;
}
}

**Comment by SGauts** [comment]
this is the app.component.ts file for which the spec file isn't being generated.

**Comment by Sanderand** [comment]
I've set up a tiny reproduction example. For me this works fine. Tests are being generated for app.component.spec.ts. Can you please follow the instructions in the readme.md and let me know the console output?

[ts-spec-bootstrapper-issue-12-tester.zip](https://github.com/mercedesbenzio/ts-spec-bootstrapper/files/3039561/ts-spec-bootstrapper-issue-12-tester.zip)
