### ISSUE TITLE
Consider using a map in file-finder

### ISSUE THREAD

**Issue by Ryuno-Ki** [mercedesbenzio/ts-spec-bootstrapper#2]
Since it increases readability, consider using a `Array.prototype.map` in https://github.com/mercedesbenzio/ts-spec-bootstrapper/blob/99fa009e2e3d6c6b9c9ee4cfda5ca31028a63906/src/file-finder.ts#L12

That is:
`const matches = files.map((file, index) => magic(file, i))` with `magic` being the body of your current for-loop.

**Comment by Sanderand** [comment]
for loop has been replaced with https://github.com/mercedesbenzio/ts-spec-bootstrapper/pull/13. Closing this issue.
